setup/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from projects.views import *

urlpatterns = [
    path("", logar_usuario, name="logar_usuario"),
    path("home", home, name="home"),
    path("cargainicial", cargainicial, name="cargainicial"),
    path("index", logar_usuario, name="logar_usuario"),
    path("profile", profile, name="profile"),
    path("deslogar_usuario", deslogar_usuario, name="deslogar_usuario"),
    path("recuperar_senha", recuperar_senha, name="recuperar_senha"),
    path("redefinir_senha", redefinir_senha, name="redefinir_senha"),
    path("usuarios", usuarios, name="usuarios"),
    path("usuarios/<opc>", usuarios, name="usuarios"),
    path("usuarios/<opc>/<pk>", usuarios, name="usuarios"),
    path("empresas", empresas, name="empresas"),
    path("empresas/<opc>", empresas, name="empresas"),
    path("empresas/<opc>/<pk>", empresas, name="empresas"),
    path("servicos", servicos, name="servicos"),
    path("servicos/<opc>", servicos, name="servicos"),
    path("servicos/<opc>/<pk>", servicos, name="servicos"),
    path("grupos", grupos, name="grupos"),
    path("grupos/<opc>", grupos, name="grupos"),
    path("grupos/<opc>/<pk>", grupos, name="grupos"),
    path("grupos/<opc>/<pk>/<grupo>", grupos, name="grupos"),
    path("itemGrupo", itemGrupo, name="itemGrupo"),
    path("itemGrupo/<opc>/<pk>", itemGrupo, name="itemGrupo"),
    path("clientes", clientes, name="clientes"),
    path("clientes/<opc>", clientes, name="clientes"),
    path("clientes/<opc>/<pk>", clientes, name="clientes"),
    path("colaboradores", colaboradores, name="colaboradores"),
    path("colaboradores/<opc>", colaboradores, name="colaboradores"),
    path("colaboradores/<opc>/<pk>", colaboradores, name="colaboradores"),
    path("valores", valores, name="valores"),
    path("valores/<opc>", valores, name="valores"),
    path("valores/<opc>/<pk>", valores, name="valores"),
    path("relatorios", relatorios, name="relatorios"),
    path("adicionar_item_servico", adicionar_item_servico, name="adicionar_item_servico"),
    path(
        "retorna_total_usuarios", retorna_total_usuarios, name="retorna_total_usuarios"
    ),
    path(
        "retorna_total_projetos", retorna_total_projetos, name="retorna_total_projetos"
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.hashers import make_password, check_password
from django.utils.translation import gettext as _

class Grupos(models.Model):
  
  def getSimNao():
    SN = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )
    return SN

  def __str__(self):
      return self.descricao

  def __unicode__(self):
      return self.descricao

  created_at = models.DateTimeField(auto_now=True)
  updated_at = models.DateTimeField(auto_now=True)
  active = models.BooleanField(default=True, verbose_name="Ativo ?")

  codigo = models.AutoField(primary_key=True)
  descricao = models.CharField(
    verbose_name="Descrição", max_length=200, null=False, blank=False
  )
  
  class Meta:
    verbose_name_plural = "Grupos de Acesso"
    ordering = ('codigo','descricao',)

class ItemGrupo(models.Model):
  
  def getRotinas():
    ROTINAS = (
        ("1", "Empresas"),
        ("2", "Grupos"),
        ("3", "Usuários"),
        ("4", "Clientes"),
        ("5", "Serviços"),
        ("6", "Colaboradores"),
    )
    return ROTINAS
  
  def __str__(self):
      return self.rotina

  def __unicode__(self):
      return self.rotina

  created_at = models.DateTimeField(auto_now=True)
  updated_at = models.DateTimeField(auto_now=True)
  
  grupo = models.ForeignKey(
    Grupos,
    on_delete=models.CASCADE,
    null=True,
    blank=True,
  )
  
  rotina = models.CharField(verbose_name="Rotina", max_length=80, choices=getRotinas())
  inclusao = models.CharField(
    verbose_name="Incluir", max_length=1, null=False, blank=False, choices=Grupos.getSimNao()
  )
  edicao = models.CharField(
    verbose_name="Editar", max_length=1, null=False, blank=False, choices=Grupos.getSimNao()
  )
  exclusao = models.CharField(
    verbose_name="Excluir", max_length=1, null=False, blank=False, choices=Grupos.getSimNao()
  )
  logs = models.CharField(
    verbose_name="Logs", max_length=1, null=False, blank=False, choices=Grupos.getSimNao()
  )
  filtro = models.CharField(
    verbose_name="Filtro", max_length=1, null=False, blank=False, choices=Grupos.getSimNao()
  )
  
  class Meta:
    verbose_name_plural = "Item do Grupo"
    ordering = ('created_at',)

class Usuario(AbstractUser):

  def getTipos():
    TIPOS = (
      ("1", "Cliente"), 
      ("2", "Colaborador"),
    )
    return TIPOS

  def set_password(self, raw_password):
    self.password = make_password(raw_password)
    self.password2 = make_password(raw_password)
    self.resetpsw = False
    self.save()
    return 

  class Meta:
    verbose_name_plural = "Usuários"
    ordering = ('user_id',)

  def __str__(self):
    return self.name

  username = None # desabilita o uso do username
  USERNAME_FIELD = 'user_id'
  
  created_at = models.DateTimeField(auto_now=True)
  updated_at = models.DateTimeField(auto_now=True)
  active = models.BooleanField(default=True, verbose_name="Usuário ativo ?")

  user_id = models.AutoField(primary_key=True)
  firstname = models.CharField(verbose_name="Primeiro Nome", max_length=20, null=False, blank=False)
  name = models.CharField(verbose_name="Nome Completo", max_length=200, null=False, blank=False)
  email = models.EmailField('E-mail', unique=True, null=False, blank=False)
  password = models.CharField(verbose_name="Senha", max_length=30, null=False, blank=False)
  password2 = models.CharField(verbose_name="Confirmação da Senha", max_length=30, null=False, blank=False)
  tipo = models.CharField(verbose_name="Tipo", max_length=1, null=False, blank=False, choices=getTipos())
  perfil = models.ForeignKey(
    Grupos,
    on_delete=models.SET_NULL,
    null=True,
    blank=True,
  )
  resetpsw = models.BooleanField(default=True, verbose_name="Altera Senha ?")
  usefilter = models.BooleanField(default=True, verbose_name="Permite o uso de Filtros ?")
  
class Empresa(models.Model):

  def getUF():
    UF = (
      ("AC", "AC"),
      ("AL", "AL"),
      ("AP", "AP"),
      ("AM", "AM"),
      ("BA", "BA"),
      ("CE", "CE"),
      ("DF", "DF"),
      ("ES", "ES"),
      ("GO", "GO"),
      ("MA", "MA"),
      ("MT", "MT"),
      ("MS", "MS"),
      ("MG", "MG"),
      ("PA", "PA"),
      ("PB", "PB"),
      ("PR", "PR"),
      ("PE", "PE"),
      ("PI", "PI"),
      ("RJ", "RJ"),
      ("RN", "RN"),
      ("RS", "RS"),
      ("RO", "RO"),
      ("RR", "RR"),
      ("SC", "SC"),
      ("SP", "SP"),
      ("SE", "SE"),
      ("TO", "TO"),
    )
    return UF

  created_at = models.DateTimeField(auto_now=True)
  updated_at = models.DateTimeField(auto_now=True)
  active = models.BooleanField(default=True, verbose_name="Empresa ativa ?")
  codigo = models.AutoField(primary_key=True)

  nome = models.CharField(
      verbose_name="Empresa", max_length=200, null=False, blank=False
  )

  cnpj = models.CharField(verbose_name="CNPJ", max_length=18, default="")
  endereco = models.CharField(verbose_name="Endereço", blank=True, max_length=250, default="")
  complemento = models.CharField(verbose_name="Complemento", blank=True, max_length=100, default="")
  cep = models.CharField(verbose_name="CEP", blank=True, max_length=10, default="")
  bairro = models.CharField(verbose_name="Bairro", max_length=80, blank=True, null=True)
  cidade = models.CharField(verbose_name="Cidade", max_length=50, blank=True, null=True)
  estado = models.CharField(verbose_name="Estado", max_length=2, choices=getUF(), blank=True, null=True)
  telefone = models.CharField(verbose_name="Telefone", max_length=20, default="")
  dados_bancarios = models.TextField(verbose_name="Informações Bancarias", null=True, blank=True, default="")
  imposto = models.DecimalField(verbose_name="% Imposto", max_digits=6, decimal_places=2,null=True, blank=True)

  def __str__(self):
    return self.nome

  class Meta:
    verbose_name_plural = "Empresas"
    ordering = ('codigo',)

class Cliente(models.Model):

  def getTipo():
    TIPO = (
      ('F', 'Pessoa Fisica'),
      ('J', 'Pessoa Juridica'),
    )
    return TIPO
  
  created_at = models.DateTimeField(auto_now=True)
  updated_at = models.DateTimeField(auto_now=True)
  active = models.BooleanField(default=True, verbose_name="Cliente ativo ?")
  codigo = models.AutoField(primary_key=True)
  nome = models.CharField(verbose_name="Nome", null=False, blank=False, max_length=200)
  cnpj = models.CharField(verbose_name="CNPJ", max_length=18)
  ie = models.CharField(verbose_name="IE", max_length=14, blank=True)
  endereco = models.CharField(verbose_name="Endereco", max_length=150, blank=True)
  complemento = models.CharField(verbose_name="Complemento", max_length=50, blank=True)
  cep = models.CharField(verbose_name="CEP", max_length=10, blank=True)
  bairro = models.CharField(verbose_name="Bairro", max_length=50, blank=True)
  cidade = models.CharField(verbose_name="Cidade", max_length=50, blank=True)
  estado = models.CharField(verbose_name="Estado", max_length=2, choices=Empresa.getUF(), default="")
  email = models.CharField(verbose_name="E-mail", max_length=100, blank=False, default="")
  email_cat = models.CharField(verbose_name="E-mail Cat", max_length=100, default="")
  usa_email_cat = models.CharField(verbose_name="Recebe E-mail Cat?", max_length=1, choices=Grupos.getSimNao(), default="")
  telefone = models.CharField(verbose_name="Telefone", max_length=20, blank=False,default="")
  contatos = models.TextField(verbose_name="Contatos", null=True, blank=True, default="")
  dados_bancarios = models.TextField(verbose_name="Informações Bancárias", null=True, blank=True, default="")
  observacoes = models.TextField(verbose_name="Observações", null=True, blank=True, default="")
  valor_hora_atual = models.DecimalField(verbose_name="Valor Hora", max_digits=6, decimal_places=2, null=True, blank=True, default=0)
  perc_desconto_atual = models.DecimalField(verbose_name="% Desconto", max_digits=6, decimal_places=2, null=True, blank=True, default=0)
  
  class Meta:
    verbose_name_plural = "Clientes"

  def __str__(self):
      return self.nome

class Servicos(models.Model):
  
  def getTipos():
    TIPOS = (
      ('Pontual', 'Pontual'),
      ('Sustentação', 'Sustentação'),
      ('Service Desk', 'Service Desk'),
      ('Projeto', 'Projeto'),
      ('Hora Adicional', 'Hora Adicional'),
    )
    return TIPOS
  
  def getEtapasComercial():
    TIPOS = (
      ('Oportunidade', 'Oportunidade'),
      ('Proposta', 'Proposta'),
      ('Fechado', 'Fechado'),
      ('Perdido', 'Perdido'),
    )
    return TIPOS
  
  def getEtapasTecnicas():
    TIPOS = (
      ('DOS16', 'DOS16'),
      ('Definição de Analista', 'Definição de Analista'),
      ('Repasse', 'Repasse'),
      ('Desenvolvimento', 'Desenvolvimento'),
      ('Validação', 'Validação'),
      ('Revisão', 'Revisão'),
      ('Acompanhamento', 'Acompanhamento'),
      ('Finalizado', 'Finalizado'),
      ('Outros', 'Outros'),
    )
    return TIPOS
  
  def getNextCodigo():
    codigo = 'ERP-%04d' % (Servicos.objects.count()+1)
    return codigo

  created_at = models.DateTimeField(auto_now=True)
  updated_at = models.DateTimeField(auto_now=True)
  codigo = models.CharField(primary_key=True, max_length=8)

  descricao = models.CharField(verbose_name="Descrição", max_length=80, null=False, blank=False)
  versao = models.CharField(verbose_name="Versão", max_length=3, null=False, blank=False)
  
  cliente = models.ForeignKey(
    Cliente,
    on_delete=models.SET_NULL,
    null=True,
    blank=True,
  )

  tipo = models.CharField(verbose_name="Tipo", max_length=20,  choices=getTipos())
  valor_hora = models.DecimalField(verbose_name="Valor Hora", max_digits=6, decimal_places=2)
  comissao = models.DecimalField(verbose_name="% Comissão", max_digits=6, decimal_places=2)
  valor_comissao = models.DecimalField(verbose_name="R$ Valor Comissao", max_digits=6,decimal_places=2,null=True, blank=True)
  imposto = models.DecimalField(verbose_name="% Imposto", max_digits=6, decimal_places=2,null=True, blank=True)

projects/templates/projects/em_construcao.html
{% extends "base.html" %}
{% block page_title %}Em desenvolvimento{% endblock page_title %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}

	<div class="row">
		<div class="col-xs-4 mb-2 mt-2 p-2">
				
			{% if message %}
				<div class="form-group">
					<p class="text-{{ type }}">{{ message }}</p>
				</div>
			{% endif %}

			<a href="{% url 'home' %}" class="btn btn-primary mt-4">Voltar</a>
				
		</div>
	</div>

{% endblock content %}

projects/templates/projects/grupos.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %}Grupos{% endblock page_title %}
{% block title %} Grupos de Acesso {% endblock title %}
{% block content %}

	{% if inclui or altera or visualiza %}
		
		{% if msgerro %}
		<div class="alert alert-danger" role="alert">
			{{ msgerro }}
		</div>
		{% endif %}
		
		{% if not visualiza %}
			<a class="mysubmit"  onclick="document.getElementById('my_form').submit();">
				<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" viewBox="0 0 16 16">
					<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
				</svg>
			</a>
		{% endif %}

		<a class="mycancel" href="{% url "grupos" %}" {% if visualiza %} style="top: 80px;" {% endif %}>
			<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
				<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
			</svg>
		</a>
			
		<form method="post" id="my_form">
			{% csrf_token %}
			{% crispy form %}
		</form>

		{% if altera %}
			<button type="button" class="btn btn-primary btn-sm mb-4 mt-4" id="md" data-bs-toggle="modal" data-bs-target="#myModal">
				Adicionar Rotina
			</button>

			<!-- Modal -->
			<form method="post" id="form2" name="form2" action="{% url 'itemGrupo' %}">
				{% csrf_token %}
				<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="itemModalLabel" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<h1 class="modal-title fs-5">Adicionar Acesso</h1>
								<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
							</div>
							<div class="modal-body">
								{% crispy form_item %}
								<input type="hidden" id="pk" name="pk" value=''>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">Cancelar</button>
								<button type="submit" class="btn btn-primary btn-sm">Confirmar</button>
							</div>
						</div>
					</div>
				</div>
			</form>
			
		{% endif %}

		{% if grid %}
			<div class="table-responsive-sm">
			
				{% if messages %}
					<div class="alert alert-danger" role="alert">
						<ul class="m-0 p-0" style="list-style: none;">
							{% for message in messages %}
								<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
							{% endfor %}
						</ul>
					</div>
				{% endif %}

				<table class="table table-sm table-striped">
					<thead>
						<tr>
							<th>Rotina</th>
							<th>Inclusão</th>
							<th>Edição</th>
							<th>Exclusão</th>
							<th>Logs</th>
							<th>Filtro</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						{% for item in grid %}
						<tr>
							<td>{{ item.get_rotina_display }}</td>
							<td>{{ item.get_inclusao_display }}</td>
							<td>{{ item.get_edicao_display }}</td>
							<td>{{ item.get_exclusao_display }}</td>
							<td>{{ item.get_logs_display }}</td>
							<td>{{ item.get_filtro_display }}</td>
							<td>
								{% if altera %}
								
									<a 	
										onclick="javascript:return confirmDeleteItem();"
										href="{% url 'grupos' opc='itemDelete' pk=item.id grupo=item.grupo_id %}"
									>
										<i class="fa fa-times fs-5 align-middle text-danger"></i>
									</a>
								{% endif %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		{% endif %}

	{% else %}
		
		{% if user.usefilter %}	
			<div class="filtro ">
				<form method="GET" id="form_filtro">
					{{ filter.form.filtro }}
					
					<a class="btnfiltro" onclick="document.getElementById('form_filtro').submit();">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
							<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
						</svg>
					</a>

					<!--<input class="filter_buttons" type="button" value="Limpar" onclick="limparCampos()" />-->
				</form>
			</div>
		{% endif %}
		
		<!-- Mensagens retornadas do messages.error -->
		{% if messages %}
			<div class="alert alert-danger" role="alert">
				<ul class="m-0 p-0" style="list-style: none;">
					{% for message in messages %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					{% endfor %}
				</ul>
			</div>
		{% endif %}
		
		<!-- botão inserir -->
		<div class="mb-2 mt-0 p-0">
			<a href="{% url 'grupos' opc='insert' %}" >
				<i class="fa fa-plus-square fa-2x"  aria-hidden="true"></i>
			</a>
		</div>
			
		<!-- lista -->
		<table class="table table-sm-responsive">
			<thead class="table-dark" >
				<tr>
					<th>Código</th>
					<th>Descrição</th>
					<th>Ativo</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				
				{% for grupo in filter.qs %}
					<tr>
						<td>{{ grupo.codigo }}</td>
						<td>{{ grupo.descricao }}</td>
						<td>{{ grupo.active }}</td>
						<td>
							<a href="{% url "grupos" opc='view' pk=grupo.codigo %}" class="mx-2">
								<i class="fa fa-eye align-middle text-dark"></i>
							</a>
							<a href="{% url "grupos" opc='edit' pk=grupo.codigo %}" class="mx-2">
								<i class="fa fa-edit align-middle text-primary"></i>
							</a>
							<a href="{% url "grupos" opc='delete' pk=grupo.codigo	 %}">
								<i class="fa fa-times fs-5 align-middle text-danger"></i>
							</a>
						</td>
					</tr>
				{% endfor %}

			</tbody>
		</table>
		
	{% endif %}
		
	<script type="text/javascript">
		const pk = document.getElementById("pk");
		var url = window.location.href.split('/')
		var last = (url.length)-1

		if (pk != null){
			pk.value = url[last];
		}
		
	</script>

	<script type="text/javascript">
		function confirmDeleteItem(){
			if( confirm('Deseja realmente remover a rotina do grupo?' )){
				return true
			}else{
				return false	
			}
		}
	</script>

{% endblock content %}

projects/templates/projects/usuarios.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %} Usuários {% endblock page_title %}
{% block title %} Usuários {% endblock title %}
{% block content %}
	
	{% if inclui or altera or visualiza %}

		{% if not visualiza %}
			<a class="mysubmit"  onclick="document.getElementById('my_form').submit();">
				<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" viewBox="0 0 16 16">
					<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
				</svg>
			</a>
		{% endif %}

		<a class="mycancel" href="{% url "usuarios" %}" {% if visualiza %} style="top: 80px;" {% endif %}>
			<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
				<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
			</svg>
		</a>

	 	<form method="post" id="my_form">
			{% csrf_token %}

			{% if messages %}
				<div class="alert alert-danger" role="alert">
					<ul class="m-0 p-0" style="list-style: none;">
						{% for message in messages %}
							<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
						{% endfor %}
					</ul>
				</div>
			{% endif %}

			<div class="accordion" id="accordionMain" >
				<div class="accordion-item">
					<h2 class="accordion-header" id="headingOne">
						<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
							Cadastro
						</button>
					</h2>
					<div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionMain">
						<div class="accordion-body">
							{% crispy form %}
						</div>
					</div>
				</div>
			</div>
			
    </form>

	{% else %}
		
		{% if user.usefilter %}	
			<div class="filtro ">
				<form method="GET" id="form_filtro">
					{{ filter.form.name }}
					
					<a class="btnfiltro" onclick="document.getElementById('form_filtro').submit();">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
							<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
						</svg>
					</a>

					<!--<input class="filter_buttons" type="button" value="Limpar" onclick="limparCampos()" />-->
				</form>
			</div>
		{% endif %}
			
			{% if messages %}
				<div class="alert alert-danger" role="alert">
					<ul class="m-0 p-0" style="list-style: none;">
						{% for message in messages %}
							<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			
			<!-- botão inserir -->
			<div class="mb-2 mt-0 p-0">
				<a href="{% url 'usuarios' opc='insert' %}" >
					<i class="fa fa-plus-square fa-2x"  aria-hidden="true"></i>
				</a>
			</div>
			
			<!-- lista -->
			<table class="table table-sm-responsive">
				<thead class="table-dark" >
					<tr>
						<th>ID</th>
						<th>Primeiro Nome</th>
						<th>Nome</th>
						<th>E-mail</th>
						<th>Tipo</th>
						<th>Perfil</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					
					{% for user in filter.qs %}
						{% if  user.active %}
							<tr class="">
						{% else %}
						<tr class="table-danger">
							{% endif %}
							<td>{{ user.user_id }}</td>
							<td>{{ user.firstname }}</td>
							<td>{{ user.name }}</td>
							<td>{{ user.email }}</td>
							<td>{{ user.get_tipo_display }}</td>
							<td>{{ user.perfil }}</td>
							<td>
								<a href="{% url "usuarios" opc='view' pk=user.email %}" class="mx-2">
									<i class="fa fa-eye align-middle text-dark"></i>
								</a>
								<a href="{% url "usuarios" opc='edit' pk=user.email %}" class="mx-2">
									<i class="fa fa-edit align-middle text-primary"></i>
								</a>
								<a
									onclick="javascript:return confirmDeleteItem('{{ user.firstname }}');" 
									href="{% url "usuarios" opc='delete' pk=user.email %}"
								>
									<i class="fa fa-times fs-5 align-middle text-danger"></i>
								</a>
							</td>
						</tr>
					{% endfor %}
					
				</tbody>
			</table>
		
	{% endif %}
	
	<script>
		document.getElementById ("id_name").placeholder = "Nome ou E-mail";

		function limparCampos(){
			document.getElementById('id_name').value='';
			document.getElementById('id_email').value='';
			document.getElementById('form_filtro').submit();
		}
	</script>

	<script type="text/javascript">
		function confirmDeleteItem(username){
			if( confirm('Deseja realmente excluir o usuário ' + username + '?' )){
				return true
			}else{
				return false	
			}
		}
	</script>


{% endblock content %}